### ISSUE TITLE
Screensaver activates when using remote app

### ISSUE THREAD

**Issue by DanTheMan827** [MrMC/mrmc#1]
If you use the Kodi remote app on the iPhone to control MrMC, the tvOS screensaver will activate

**Comment by MrMC** [comment]
you can keep this open, we will close it when the fix hits code

**Comment by MrMC** [comment]
humm, this is difficult. a) there is no way to know when tvos screensaver activates, the once it kicks in, there seems to be no way to kick out of it. 

setIdleTimerDisabled = YES prevents entry but once in setting setIdleTimerDisabled=NO has no effect.

suggestions ?

**Comment by MrMC** [comment]
got it :)
