### ISSUE TITLE
Support for VP9 hardware decoding at 4K resolution & 60 fps on Android?

### ISSUE THREAD

**Issue by Hedda** [MrMC/mrmc#11]
Hi MrMC, can you maybe confirm if MrMC media center supports VP9 hardware decoding at 2160p resolution & 60 frames per second?

See example with sample links:

http://www.cnx-software.com/2016/06/07/4k-vp9-video-playback-in-amlogic-s905x-based-nexbox-a5-android-tv-box/

4K VP9 @ 60 fps should on paper be support by both Nvidia Shield TV (GPU), the new Amlogic S905X (VPU), and the new Hi3798C V200 (VPU) SoC, but does MrMC?

**Comment by MrMC** [comment]
Need a direct link to a file to test. That example/sample links leads nowhere.

**Comment by Hedda** [comment]
Sorry no direct download link, but 4K VP9 videos can relativly easily be downloaded directly from YouTube using the youtube-dl Python script from https://rg3.github.io/youtube-dl/ (which is also also available as a  Windows executable that includes Python).

Find the VP9 2160p video first:

 youtube-dl URL --list-formats

Download it:

 youtube-dl URL -f format_code

URLs to specific examples which have 4K VP9 videos: 

https://www.youtube.com/watch?v=7Vk3qJ4LwAw
https://www.youtube.com/watch?v=XCbir1vyUA0
https://www.youtube.com/watch?v=doa9asyxlMU
https://www.youtube.com/watch?v=I7CycuMpQ3w
https://www.youtube.com/watch?v=UceRgEyfSsc

**Comment by Stane1983** [comment]
I can confirm that 4K VP9 (1st link) is working just fine on Amlogic S912, Android 7. If not working then firmware is based on old(er) SDK where some bugs are still not fixed. Amlogic also released month or so ago Marshmallow update where they fixed passtrough too. It's only up to ODMs if they will bother preparing new SDK (which I doubt).

**Comment by MrMC** [comment]
closing as working.
