### ISSUE TITLE
wrong display size on fireOS tablets

### ISSUE THREAD

**Issue by MrMC** [MrMC/mrmc#13]
On fireOS tables (hd for example), the 'native display' is reported as 1280 x 752 which is screen minus task bar at bottom. The real size is 1280 x 800. As the task bar is hidden, this results in the display mapping being slightly off and touches been to be offset up a little to get seen.

TODO: fix it such that we use the full size as the task bar is hidden and slides up over gui when needed.

**Comment by koying** [comment]
Did you try getWindow().getDecorView().getWidth() ?

**Comment by MrMC** [comment]
getDecorView returns the size assuming the task bar is up.

**Comment by MrMC** [comment]
should be fixed
