### ISSUE TITLE
Add native Emby client

### ISSUE THREAD

**Issue by MrMC** [MrMC/mrmc#19]
Integrate native Emby client into MrMC. Nuff' said.

**Comment by amet** [comment]
Rock Paper Scissors who gets to start? :))

**Comment by MrMC** [comment]
In progress...

**Comment by MrMC** [comment]
done - login by user/pass
done - pull/display/play movies

todo - server syncing/update items
todo - login by pin
todo - tvshows
todo - music

**Comment by MrMC** [comment]
done - login by user/pass
done - log in by pin
done - pull/display/play movies
done - tvshows
done - server syncing/update items
done - music

moving to testflight now

**Comment by MrMC** [comment]
released
