### ISSUE TITLE
MrMC not filling in Dolby or Video tags

### ISSUE THREAD

**Issue by mychaelp** [MrMC/mrmc#24]
I finally used the library feature with MrMC on my Gen1 Fire TV. About 1% of my movies have the tags for dolby or dts and the type of video/aspect. If I play one for a second and stop it, then it shows up. I'd rather not do that for all 300 or so. Is there a setting I'm missing. 
Moving this request for support from the regular website.
Thanks for this great program, just this issue is bugging me.

**Comment by amet** [comment]
not an issue here, but it does popup occasionally in forms, I think we had 2 more complaints.

I have been looking at code and dont see any issues on my side, tried setting up new library local and on MySQL server and all seems to be ok.

will dig in deeper to see if anything comes up.

**Comment by mychaelp** [comment]
I refreshed the library last night with 3 new items, non showed the tags. Then once I played each for just a second, they were there. If you find anything when testing, let me know. Otherwise the app still works great. Just wish there were a few more layout options on the skin for movies. Something to show more of the fanart with the summary slightly embedded and not blocked. Looking forward to the one you guys discussed might be coming sometime. thanks for your reply and for the great app

**Comment by MrMC** [comment]
Pushed up a possible fix into the current test flight series. Are you in Testflight ? Ah, Gen1 Fire TV. it will be tomorrow when that hits amazon.

**Comment by mychaelp** [comment]
No, I'll wait for the official update. I'm now using MrMC exclusively and just have my old XBMC on my Fire TV as a backup just in case. Thanks for the update on this, it's really appreciated. As new versions come out I'll be sure to donate if there's an easy way. It's great to have something that's actively worked on. And it just works....

**Comment by mychaelp** [comment]
I e-mailed per the main website to get on the testflight. looking forward to trying it out. Thanks

**Comment by MrMC** [comment]
closed as working
