### ISSUE TITLE
two minor version developers close them eyes on my pm3.hd skin correction

### ISSUE THREAD

**Issue by BAGAsss** [MrMC/mrmc#25]
is it right thing?

**Comment by amet** [comment]
really? where is the PR for your skin development?

**Comment by BAGAsss** [comment]
really. i connected to davilla and gave him url to check my corrections. after all he told he have no time.
I`ll replace my corrections to https://github.com/MrMC/mrmc/pulls in couple days. (if i will have right to do it)

**Comment by amet** [comment]
Rebase your branch, fix it up so it's all in one commit and bump up the version number in addon.xml for clarity sake. 

Once you create pull request here, we will review it and pull into main branch

**Comment by BAGAsss** [comment]
i understood and making it
