### ISSUE TITLE
VC1 on firetv.

### ISSUE THREAD

**Issue by MrMC** [MrMC/mrmc#29]
dropped frames when playing VC-1 in MKV container on FireTV G2

https://forum.mrmc.tv/viewtopic.php?f=17&t=1134

**Comment by waldo22** [comment]
Fire TV G1 as well.

**Comment by waldo22** [comment]
This is still happening.  Wonder Woman (2009) cartoon is VC-1 and is unwatchable.
https://www.themoviedb.org/movie/15359-wonder-woman
Interestingly, disabling Mediacodec and Mediacodec (surface) made no difference, so it's acting as if it's not using Hardware Acceleration at all.

**Comment by mihaiqc** [comment]
Reporting VC-1 in MKV container gets transcoded and can't directplay.

Observable in Rick & Morty. Also the case in other Kodi forks.

**Comment by davilla** [comment]
https://forum.mrmc.tv/viewtopic.php?f=17&t=1134#p10618

No hw VC1 decoder on firetv...
