### ISSUE TITLE
ATV AirPlay audio out quality issues

### ISSUE THREAD

**Issue by nedtheelephant** [MrMC/mrmc#4]
When an AirPlay speaker is set as the audio output for the Apple TV, the audio quality is poor when playing music. There are obvious pops and crackles throughout the song.

**Comment by MrMC** [comment]
MrMC log ?

**Comment by nedtheelephant** [comment]
http://pastebin.com/RwdesaaM

**Comment by nedtheelephant** [comment]
Perhaps something to do with lines 214-217 in that log? AirPlay has a max bitrate of 44100 - I have this set as the max bitrate in MrMC (I've tried all the options as well with no change). Is it still trying to force 48000?

**Comment by MrMC** [comment]
enable debug logging might show more info.

**Comment by nedtheelephant** [comment]
I did, I think. It is turned on line 93. Sorry if I'm misunderstanding.

**Comment by nedtheelephant** [comment]
I have also some logs from Kodi tvos 30 December build which is before Memphiz pulled in some MrMC changes that caused later builds of Kodi tvos to have this same AirPlay issue. 
http://xbmclogs.com/pfoczzbdq
So with these logs AirPlay is working nicely - I think line 42 and 1075-1077 are interesting as here sample rate 44100 is also availble (line 42) as it wasn't in MrMC and it is able to output using it (lines 1075-1077).

**Comment by MrMC** [comment]
interesting

**Comment by nedtheelephant** [comment]
Seems to be fixed on version 1.3 from the TVOS App Store and logs suggest that 41k sample rate is working fine now. Well done!

**Comment by MrMC** [comment]
thanks, closing.
