### ISSUE TITLE
Massive MrMC problem: Outdated DVDFactoryInputStream.cpp (lacking critical Kodi fixes)

### ISSUE THREAD

**Issue by ghost** [MrMC/mrmc#41]
## MrMC is lacking a critical fix to its internet-streaming code, which was added to Kodi on August 27th, 2016.

Internet streaming works perfectly in Kodi but not in MrMC. After six hours of research, I finally found "the problem" with MrMC. Here is some critical code that really needs to be merged into MrMC as soon as possible:

https://github.com/xbmc/xbmc/pull/10236/files

Without the fix:

- `http://a.com/channel/1` redirects (via `Location:` header) to `http://other.com/live/master.m3u8`.
- Kodi/MrMC thinks that the base-URL is `http://a.com/channel/`.
- The `master.m3u8` uses relative URLs (which is very common), such as `chunk23823.ts`.
- Kodi/MrMC tries to open `http://a.com/channel/chunk23823.ts`. Wrong!

With the fix:

- `http://a.com/channel/1` redirects (via `Location:` header) to `http://other.com/live/master.m3u8`.
- Kodi/MrMC detects the new, redirected `http://other.com/live/master.m3u8` "final URL" (via the pull request code shown above) and uses `http://other.com/live/` as the new "base URL" instead.
- The `master.m3u8` uses relative URLs (which is very common), such as `chunk23823.ts`.
- Kodi/MrMC successfully opens `http://other.com/live/chunk23823.ts`. Awesome!

This fix matters severely, because many IPTV services use redirects to resolve the final location. For example, something like `http://someservice.com/channel.php?id=123&user=abc&password=def` which then sends a Location redirect to the actual stream URL.

That's also common in scenarios where playlists "simplify" the public channel URLs by hiding them behind redirects so that any necessary changes to the "real channel URLs" can be done transparently on the server-end without needing to distribute modified playlists to the clients, since clients just access `http://something/channel/1` instead of the complex, real URLs. In fact, that is what I am using redirects for. Public channels change URLs frequently and it's better to use redirects. And it works perfectly in Kodi since they fixed the redirection bug a while ago...

If you search the official kodi forums for "redirect m3u8" or similar, you will see that tons of people use redirection-server backends, so merging the above pull request is really a critical fix for MrMC's IPTV streaming ability. Many situations won't work at all in MrMC until it fixes this bug too.

Thanks for MrMC. I hope this fix can be merged pretty soon (and submitted to AppleTV) so that MrMC becomes as good as Kodi at streaming IPTV. 👍  :-) Right now, MrMC is a dead-end for streaming... but luckily this fix is simple... Here's hoping it can be done soon!

**Comment by MrMC** [comment]
fixed in testflight for 3.7.0
