### ISSUE TITLE
Plex In Progress Widgets

### ISSUE THREAD

**Issue by Tgxcorporation** [MrMC/mrmc#42]
I've noticed that plex in progress widgets for movies and episodes (8010/8011) have a wrong sort order. I'm not sure if this issue applies only to plex widgets.
No matter which movie or episode you've just watched, its position in the in progress widget does not change. Imho the latest played video should always be the first.

Thanks

Tgx

**Comment by amet** [comment]
got it, fixed for 3.5.1... thanks!

**Comment by Tgxcorporation** [comment]
Thanks

**Comment by amet** [comment]
Did you try it in 3.5.1?

**Comment by Tgxcorporation** [comment]
It's ok now.

Thanks

Tgx
