### ISSUE TITLE
Crash when trying to play some files

### ISSUE THREAD

**Issue by AndyPeterman** [MrMC/mrmc#51]
I have a few files that crash MrMC on an ATV when I attempt to play them.  They all play fine in other players, but crash in MrMC before it actually starts playing.  Here's a link to one of them (about 77 MB - I can possibly find a smaller one if necessary):

https://www.dropbox.com/s/qk6gg86rw1eupml/Craigs%20List%20-%20Weird%20Al.mp4?dl=0

Here's where it's crashing:

void
CDVDVideoCodecVideoToolBox::ValidateVTSessionParameterSetsForRestart(uint8_t *pData, int iSize)
{
  // temp bypass of hevc
  if (m_hints.codec == AV_CODEC_ID_HEVC)
    return;

  static uint64_t frameCount = 0;

  size_t spsCount = 0;
  size_t ppsCount = 0;
  size_t vpsCount = 0;

  // pData is in bit stream format, 32 size (big endian), followed by NAL
  uint8_t *data = pData;
  uint8_t *dataEnd = data + iSize;
  // do a quick search for parameter sets in this frame
  while (data < dataEnd)
  {
    int nal_size = BS_RB32(data);      **DVDPlayerVideo (60): EXC_BAD_ACCESS (code=1, address=0x9ab8e59c)**
    data += 4;
    if (m_hints.codec == AV_CODEC_ID_H264)
    ...

Let me know if this is the wrong place to report bugs like this.

Thanks!

**Comment by MrMC** [comment]
This is fine, will look into why.

**Comment by MrMC** [comment]
Fixed, never have seen a 2-byte NAL avcC format in the wild. thanks for reporting. The fix will be in next TestFlight for 3.7.0

**Comment by MrMC** [comment]
Oh and thanks a bunch for a great music video, made chasing this quite fun :)

**Comment by AndyPeterman** [comment]
Fantastic!  Glad you enjoyed the "test" file. :)
