### ISSUE TITLE
AirPods/Bluetooth Headsets and 5.1

### ISSUE THREAD

**Issue by ersan** [MrMC/mrmc#58]
When you connect AirPods or I assume any other Bluetooth headset to an Apple TV when it is configured for surround sound (and with surround sound source audio), MrMC will only play the L and R channels through the AirPods instead of downmixing to stereo.  You can't hear dialogue from the center channel via the BT headphones.

**Comment by ersan** [comment]
Debug log: https://pastebin.com/zpi4dW21

**Comment by davilla** [comment]
fixed in testflight for v3.7.0
