### ISSUE TITLE
Add native plex client

### ISSUE THREAD

**Issue by MrMC** [MrMC/mrmc#9]
Integrate native plex client into MrMC. Nuff' said.

**Comment by Vlaves** [comment]
That would be just awsome :) I'm hoping in that way of incorporating the funtionality from https://github.com/RasPlex/OpenPHT :)

**Comment by MrMC** [comment]
Status update: Coming along nicely. It's in Testflight for pending v2.4 release. Maybe a week or two away from release.

**Comment by MrMC** [comment]
Initial integration is finished :)
